# Generated by Django 4.1.7 on 2023-03-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='validated',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
