# Generated by Django 4.1.7 on 2023-03-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homemed', '0002_alter_doctor_validated_alter_invitation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='description',
        ),
    ]
