# Generated by Django 4.1.7 on 2023-03-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homemed', '0003_remove_doctor_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='date_of_birth',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_birth',
            new_name='birthday',
        ),
    ]
