# Generated by Django 4.1.7 on 2023-03-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemed', '0004_rename_date_of_birth_doctor_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='birthday',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
