# Generated by Django 4.1.7 on 2023-03-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemed', '0007_remove_appointment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
