# Generated by Django 4.1.7 on 2023-03-21 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homemed', '0009_appointment_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fileId', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('birthYear', models.PositiveIntegerField()),
                ('birthMonth', models.PositiveIntegerField()),
                ('birthDay', models.PositiveIntegerField()),
                ('birth_town', models.CharField(max_length=255)),
                ('birth_county', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('chronicConditions', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientless',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='county',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='county',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
