# Generated by Django 4.1.7 on 2023-03-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homemed', '0010_consultation_medicalrecord_appointment_patientless_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='lastName',
        ),
    ]
