# Generated by Django 4.1.7 on 2023-03-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homemed', '0012_remove_medicalrecord_birthday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='date',
            new_name='birthday',
        ),
    ]
