# Generated by Django 4.1.7 on 2023-03-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homemed', '0013_rename_date_medicalrecord_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='address',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='county',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='town',
        ),
    ]
