# Generated by Django 4.1.7 on 2023-03-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemed', '0015_rename_chronicconditions_medicalrecord_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='allergies',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='chronicDiseases',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='currentMedications',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='familyHistory',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='personalHistory',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='surgeries',
            field=models.TextField(default=''),
        ),
    ]
