# Generated by Django 4.1.7 on 2023-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemed', '0018_remove_medicalrecord_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='availableTimeEnd',
            field=models.CharField(default='23:59', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='availableTimeStart',
            field=models.CharField(default='00:00', max_length=255),
        ),
    ]
