# Generated by Django 4.1.7 on 2023-03-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemed', '0020_remove_medicalrecord_currentmedications'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='currentMedications',
            field=models.TextField(default=''),
        ),
    ]
