# Generated by Django 4.1.7 on 2023-03-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemed', '0022_alter_patient_availabletimeend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='availableTimeEnd',
            field=models.PositiveIntegerField(default=23),
        ),
    ]
