# Generated by Django 4.1.7 on 2023-03-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemed', '0024_alter_patient_availabletimeend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='scheduledTime',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduledDate',
            field=models.DateField(),
        ),
    ]
